trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Models/SubscribeForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlanguruSubscription.Models
{
    public class SubscribeForm
    {
        public string Coupen_Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Subscriber_Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string RecurlyToken { get; set; }
        public string PreferedLanguage { get; set; }
        //subscribe plan related thing
        public string PlanCode { get; set; }
        public string PlanName { get; set; }
        public string PlanRate { get; set; }
        public string PlanFrequency { get; set; }
        public int PlanTypeId { get; set; }
        //addon related detail
        public string AddOnCode { get; set; }
        public string AddOnName { get; set; }
        public double AddOnUnitAmount { get; set; }
        public int Number_Of_Addon { get; set; }
        //coupon code list
        //public List<Recurly.RecurlyAccountCoupon> CoupenList { get; set; }
        public List<RecurlyNew.Coupon> CoupenList { get; set; }
    }
}

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Controllers/SelectSubscriptionController.cs
using PlanguruSubscription.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlanguruSubscription.Models;
using PlanguruSubscription.Modules;
using System.Data;
//using Recurly;
using RecurlyNew;
using System.Data.Entity.Validation;
using LicenceService;
using System.Xml;

namespace PlanguruSubscription.Controllers
{
    public class SelectSubscriptionController : Controller
    {
        private Utility utility = new Utility();
        private Common common = new Common();
        private CustomerServiceProvider customerserviceprovider;
        private XMLlisenceProvider licenseprovider;
        private ICustomerRepository customerRepository;
        private ISubscriptionPlanRepository subscriptionPlanRepository;

        public SelectSubscriptionController()
        {
            this.customerRepository = new CustomerRepository(new DataAccess());
            this.subscriptionPlanRepository = new SubscriptionPlanRepositoy(new DataAccess());
        }

        public SelectSubscriptionController(ISubscriptionPlanRepository subscriptionPlanRepository)
        {
            this.subscriptionPlanRepository = subscriptionPlanRepository;
        }

        public SelectSubscriptionController(ICustomerRepository customerRepository)
        {
            this.customerRepository = customerRepository;
        }

        //
        // GET: /SelectSubscription/

        public ActionResult ChooseSubscription()
        {
            return View();
        }

        public ActionResult BusinessSignup()
        {
            return View();
        }

        public ActionResult AdvisorSignup()
        {
            return View();
        }

        public ActionResult Subscribe(int selectedPlan)
        {

            try
            {
                SubscribeForm subscribeModel = new SubscribeForm();
                var subscriptionPlan = utility.SubscriptionPlanRepository.GetSubscriptionPlan(selectedPlan);
                var RecurlySubscriptionPlan = RecurlyNew.Plans.Get(subscriptionPlan.Plan);

                subscribeModel.PlanCode = RecurlySubscriptionPlan.PlanCode;
                subscribeModel.PlanName = RecurlySubscriptionPlan.Name;
                subscribeModel.PlanRate = subscriptionPlan.Cost_of_Subscription.ToString();
                subscribeModel.PlanTypeId = subscriptionPlan.PlanTypeId;
                if (RecurlySubscriptionPlan.AddOns.All.Count > 0)
                {
                    subscribeModel.AddOnName = RecurlySubscriptionPlan.AddOns.All[0].Name.ToString();
                    subscribeModel.AddOnUnitAmount = RecurlySubscriptionPlan.AddOns.All[0].UnitAmountInCents.FirstOrDefault().Value / 100;
                    subscribeModel.AddOnCode = RecurlySubscriptionPlan.AddOns.All[0].AddOnCode.ToString();
                }
                if (RecurlySubscriptionPlan.PlanIntervalLength == 1)
                {
                    subscribeModel.PlanFrequency = "month";
                }
                if (RecurlySubscriptionPlan.PlanIntervalLength == 12)
                {
                    subscribeModel.PlanFrequency = "12 months";
                }
               // subscribeModel.CoupenList = RecurlyNew.Coupons.List(Coupon.CouponState.Redeemable).All().ToList();
                subscribeModel.CoupenList = RecurlyNew.Coupons.List(Coupon.CouponState.Redeemable).All.ToList();
                string subscription = string.Format("{0}={1}", "subscription%5Bplan_code%5D", subscriptionPlan.Plan);



                ViewBag.Signature = PlanguruSubscription.DAL.Utility.SignWithParameters(subscription);
                ViewBag.AccountCode = PlanguruSubscription.DAL.Utility.CheckAccountCodeOnRecurly((utility.CustomerRepository.GetCustomer().Max(c => c.CustomerId)) + 1);
                ViewBag.Plan = subscriptionPlan.Plan.ToString();

                TempData["AccountCode"] = ViewBag.AccountCode.ToString();
                Logger.Log.Info(string.Format("Subscribe Execution Done"));
                return View(subscribeModel);
            }
            catch (DataException dataEx)
            {
                TempData["ErrorMessage"] = string.Concat("Error occured during loading subscription plan -", dataEx.Message);
                Logger.Log.Error(string.Format("Error occured during loading subscription plan - {0} " + Environment.NewLine + "Stack Trace: {1} ", dataEx.Message, dataEx.StackTrace));
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = string.Concat("Unable to Subscribe()-", ex.Message);
                Logger.Log.Error(string.Format("\\n Unable to Subscribe() with Message- {0} " + Environment.NewLine + "Stack Trace: {1} ", ex.Message, ex.StackTrace));
                return View();
            }
            finally
            {
                Logger.Log.Info(string.Format("Subscribe() Execution Ended"));
            }

        }

        [HttpPost]
        public ActionResult Subscribe(SubscribeForm subscribeForm)
        {
            Customer customer = null;
            int AccountCode = 0;
            int newUserAccountCode = 0;
            User userInfo = null;
            string username = string.Empty;
            int licensecustomerid = 0;
            SubscriptionPlan plan = null;
            XmlNode node = null;
            try
            {
                Logger.Log.Info(string.Format("Home - Subscription Execution Started"));

                if (((TempData["AccountCode"] != null)))
                {
                    AccountCode = Convert.ToInt32(TempData["AccountCode"]);

                }

                if (((TempData["AccountCode"] != null)))
                {

                    //RecurlyAccount account = new Recurly.RecurlyAccount(AccountCode.ToString());
                    RecurlyNew.Account account = new RecurlyNew.Account(AccountCode.ToString());
                    account.CompanyName = subscribeForm.Subscriber_Name;
                    account.Email = subscribeForm.Email;
                    account.FirstName = subscribeForm.First_Name;
                    account.LastName = subscribeForm.Last_Name;
                    account.AcceptLanguage = subscribeForm.PreferedLanguage;
                    account.Create();


                    //RecurlyBillingInfo BillingInfo = new Recurly.RecurlyBillingInfo(account);
                    RecurlyNew.BillingInfo BillingInfo = new RecurlyNew.BillingInfo(account);
                    BillingInfo.TokenId = subscribeForm.RecurlyToken;
                    BillingInfo.Create();

                    // RecurlyAccount accountInfoFromRecurly = RecurlyAccount.Get(AccountCode.ToString());
                    RecurlyNew.Account accountInfoFromRecurly = RecurlyNew.Accounts.Get(AccountCode.ToString());
                    Logger.Log.Info("Account Information is successfully submitted in Recurly for Account Id =" + accountInfoFromRecurly.AccountCode + " and Status is = " + accountInfoFromRecurly.State);
                    // RecurlyBillingInfo billingInfoFromRecurly = RecurlyBillingInfo.Get(AccountCode.ToString());
                    RecurlyNew.BillingInfo billingInfoFromRecurly = RecurlyNew.BillingInfo.Get(AccountCode.ToString());
                    Logger.Log.Info("Billing Information is successfully submitted in Recurly for Account Id =" + billingInfoFromRecurly.AccountCode);
                    RecurlyNew.Plan RecurlySubscriptionPlan = RecurlyNew.Plans.Get(subscribeForm.PlanCode);

                    //RecurlySubscription subscription = new RecurlySubscription(account);
                    //subscription.PlanCode = subscribeForm.PlanCode;
                    string CouponCode = subscribeForm.Coupen_Code != null ? subscribeForm.Coupen_Code.ToLower() : null;
                    //subscription.Account = accountInfoFromRecurly;
                    //if (subscribeForm.Number_Of_Addon > 0)
                    //{
                    //    subscription.AddOn = new RecurlyAddOn();
                    //    subscription.AddOn.add_on_code = subscribeForm.AddOnCode;
                    //    subscription.AddOn.quantity = subscribeForm.Number_Of_Addon;
                    //    subscription.AddOn.unit_amount_in_cents = Convert.ToInt32(subscribeForm.AddOnUnitAmount * 100);
                    //}

                    //subscription.CreateSubscription();
                    RecurlyNew.Subscription subscription = new RecurlyNew.Subscription(accountInfoFromRecurly, RecurlySubscriptionPlan, "USD", CouponCode);
                    if (subscribeForm.Number_Of_Addon > 0)
                    {
                        subscription.AddOns.Add(subscribeForm.AddOnCode, subscribeForm.Number_Of_Addon, Convert.ToInt32(subscribeForm.AddOnUnitAmount * 100));
                    }
                    subscription.Create();
                    RecurlyNew.Subscription subscriptionInfoFromRecurly = RecurlyNew.Subscriptions.Get(subscription.Uuid);


                    // RecurlySubscription subscriptionInfoFromRecurly = RecurlySubscription.Get(AccountCode.ToString());
                    Logger.Log.Info("Successfully get Recurly Account Code from Recurly API,Account Id is =" + subscriptionInfoFromRecurly.Account.AccountCode + "Status is = " + subscriptionInfoFromRecurly.State);
                    int numberOfAddOn = subscriptionInfoFromRecurly.AddOns.All.Count == 0 ? 0 : subscriptionInfoFromRecurly.AddOns.All.FirstOrDefault().Quantity;

                    if ((subscriptionInfoFromRecurly != null))
                    {
                        //RecurlyAccount accountInfo = RecurlyAccount.Get(AccountCode.ToString());
                        //Logger.Log.Info("Account Information is successfully submitted in Recurly for Account Id =" + accountInfo.AccountCode + " and Status is = " + accountInfo.State);
                        //RecurlyBillingInfo billingInfo = RecurlyBillingInfo.Get(AccountCode.ToString());

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/SelectSubscription/AdvisorSignup.cshtml
@model PlanguruSubscription.Models.SubscriptionPlan
@{
    ViewBag.Title = "AdvisorSignup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />

<div id="billing-info" class="section">
    <div id="choose_subscription_container">
        <h2 class="heading" style="margin-left:40px;">
            PlanGuru for Advisors:
        </h2>
        <br />
        <div style="width:90%;margin:0px 0px 40px 40px;display:inline-block;">
            <br />
            <span>Choose the subscription plan that best fits your needs:</span>
            <br />
            <br />
            <table style="width:660px">
                <tbody>
                    <tr>
                        <td style="width:330px;padding-right:20px;">
                            <h3>@Html.RadioButton("subscription_plan", 5, new { @group = "subscription_plan", style = "width:auto;" })<strong>Monthly&nbsp;Subscription&nbsp;&nbsp;$99</strong></h3>

                            <p style="width:300px;">Includes 1 user of PlanGuru, Advanced Reporting Excel Add-in and PlanGuru Analytics</p>
                            <h4>                                
                                <strong>
                                    Additional Users can be purchased on the next page for $29.
                                </strong>
                            </h4>
                        </td>
                        <td style="width:330px">
                            <h3>@Html.RadioButton("subscription_plan", 6, new { @group = "subscription_plan", style = "width:auto;" })&nbsp;<strong>Annual&nbsp;Subscription&nbsp;$899&nbsp;</strong></h3>

                            <p style="width:300px;">Includes 1 user of PlanGuru, Advanced Reporting Excel Add-in and PlanGuru Analytics</p>

                            <h4>
                                <strong>
                                    Additional Users can be purchased on the next page for $299.
                                </strong>
                            </h4>
                        </td>
                    </tr>
                </tbody>
            </table>
            <br />
            <br />


            <div class="float-right">
                <input type="submit" value="Proceed to sign-up page" class="secondbutton_example" />
            </div>
        </div>
    </div>


    @*<div id="choose_subscription_container">
        <h2 class="heading">
            PlanGuru Analytics Subscription Plan:
        </h2>

        <div style="width:90%;margin:0px 0px 40px 40px;display:inline-block;">
            <br />
            <span>Choose the subscription plan that best fits your needs. We offer two types of subscriptions.</span>
            <p>@Html.RadioButton("subscription_plan", 5, new { @group = "subscription_plan", style = "width:auto;" })Accountants/Adviser Plan - Monthly</p>
            <p>
                <div style="margin:0 0 0 20px;">
                    This plan starts at $59 per month and includes one user. Adding additional users will add $29 to the
                    total monthly subscription cost.
                </div>
            </p>
            <br />
            <p>@Html.RadioButton("subscription_plan", 6, new { @group = "subscription_plan", style = "width:auto;" })Accountants/Adviser Plan - Annual</p>
            <p>
                <div style="margin:0 0 0 20px;">
                    This plan starts at $599 per year and includes one user. Adding additional users will add $249 to the total
                    yearly subscription cost.
                </div>
            </p>
            <br />
            <div class="float-right">
                <input type="submit" value="Proceed to sign-up page" class="secondbutton_example" />
            </div>
        </div>
    </div>*@

    <div style="float:left;margin-left:20px;">
        @if (((string)TempData["Message"] != null))
        {

            <label class="success">
                @TempData["Message"].ToString()
            </label>
        }
        @if (((string)TempData["ErrorMessage"] != null))
        {
            <label class="error">
                @TempData["ErrorMessage"].ToString()
            </label>
        }

    </div>

</div>
<script type="text/javascript" language="javascript">

    $(".secondbutton_example").click(function () {

        var selectedPlan = $('input[name=subscription_plan]:checked').val();

        if (selectedPlan == undefined) {

            $.msgBox({
                title: "Subscription Plan",
                content: "Please select plan to subscribe.",
                type: "info",
                buttons: [{ value: "Ok"}],
                success: function (result) {
                },
                afterShow: function () { $('[name=Ok]').focus(); }
            });

        }

        if (selectedPlan == 5) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 5})';
        }
        else if (selectedPlan == 6) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 6})';
        }

    });

</script>

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/SelectSubscription/BusinessSignup.cshtml
@model PlanguruSubscription.Models.SubscriptionPlan
@{
    ViewBag.Title = "BusinessSignup";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />

<div id="billing-info" class="section">
    <div id="choose_subscription_container">
        <h2 class="heading" style="margin-left:40px;">
            PlanGuru for Businesses:
        </h2>
        <br/>
        <div style="width:90%;margin:0px 0px 40px 40px;display:inline-block;">
            <br />
            <span>Choose the subscription plan that best fits your needs:</span>
            <br/>
            <br/>
            <table style="width:660px">
                <tbody>
                    <tr>
                        <td style="width:330px;padding-right:20px;">
                            <h3>@Html.RadioButton("subscription_plan", 3, new { @group = "subscription_plan", style = "width:auto;" })<strong>Monthly&nbsp;Subscription&nbsp;&nbsp;$99</strong></h3>

                            <p style="width:300px;">Includes 1 user of PlanGuru, Advanced Reporting Excel Add-in and PlanGuru Analytics</p>
                            <h4>
                                <strong>
                                    Additional Users can be purchased on the next page for $29.
                                </strong>
                            </h4>
                        </td>
                        <td style="width:330px">
                            <h3>@Html.RadioButton("subscription_plan", 4, new { @group = "subscription_plan", style = "width:auto;" })&nbsp;<strong>Annual&nbsp;Subscription&nbsp;$899&nbsp;</strong></h3>

                            <p style="width:300px;">Includes 1 user of PlanGuru, Advanced Reporting Excel Add-in and PlanGuru Analytics</p> 

                            <h4 >
                                <strong>
                                    Additional Users can be purchased on the next page for $299.
                                </strong>
                            </h4>
                        </td>
                    </tr>
                </tbody>
            </table>
            <br/>
            <br/>

       
            <div class="float-right">
                <input type="submit" value="Proceed to sign-up page" class="secondbutton_example" />
            </div>
        </div>
    </div>

    <div style="float:left;margin-left:20px;">
        @if (((string)TempData["Message"] != null))
        {

            <label class="success">
                @TempData["Message"].ToString()
            </label>
        }
        @if (((string)TempData["ErrorMessage"] != null))
        {
            <label class="error">
                @TempData["ErrorMessage"].ToString()
            </label>
        }

    </div>

</div>
<script type="text/javascript" language="javascript">

    $(".secondbutton_example").click(function () {

        var selectedPlan = $('input[name=subscription_plan]:checked').val();

        if (selectedPlan == undefined) {

            $.msgBox({
                title: "Subscription Plan",
                content: "Please select plan to subscribe.",
                type: "info",
                buttons: [{ value: "Ok"}],
                success: function (result) {
                },
                afterShow: function () { $('[name=Ok]').focus(); }
            });

        }
        if (selectedPlan == 3) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 3})';
        }
        else if (selectedPlan == 4) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 4})';
        }

    });

</script>

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/SelectSubscription/ChooseSubscription.cshtml
@model PlanguruSubscription.Models.SubscriptionPlan
@{
    ViewBag.Title = "ChooseSubscription";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />

<div id="billing-info" class="section">
    <div id="choose_subscription_container">
        <h2 class="heading">
            PlanGuru Analytics Subscription Plan:
        </h2>

        <div style="width:90%;margin:0px 0px 40px 40px;display:inline-block;">
            <br />
            <span>Choose the subscription plan that best fits your needs. We offer two types of subscriptions.</span>
            <p>@Html.RadioButton("subscription_plan", 1, new { @group = "subscription_plan", style = "width:auto;" })Per User Plan</p>
            <p><div style="margin:0 0 0 20px;">This plan starts at $19.95 a month and includes one user. Adding additional users will add $19.95 per user to the total monthly subscription cost.</div></p>
            <br />
            <p>@Html.RadioButton("subscription_plan", 2, new { @group = "subscription_plan", style = "width:auto;"})Premium Group Plan</p>
            <p>
                <div style="margin:0 0 0 20px;">
                    This plan includes 4 users and start at $59.95 a month. In addition to a lower per user cost this plan also makes our
                    "Branding" feature available. This feature allows you to customize your PlanGuru Analytics subscription with your own custom firm branding.
                    After the 4th user adding additional users will add 14.95 per user to the total monthly subscription cost.
                </div>
            </p>
            <br />
            <div class="float-right">
                <input type="submit" value="Proceed to sign-up page" class="secondbutton_example" />
            </div>
        </div>
    </div>

    <div style="float:left;margin-left:20px;">
        @if (((string)TempData["Message"] != null))
        {

            <label class="success">
                @TempData["Message"].ToString()
        </label>
        }
        @if (((string)TempData["ErrorMessage"] != null))
        {
            <label class="error">
                @TempData["ErrorMessage"].ToString()
        </label>
        }

    </div>

</div>
<script type="text/javascript" language="javascript">

    $(".secondbutton_example").click(function () {

        var selectedPlan = $('input[name=subscription_plan]:checked').val();

        if (selectedPlan == undefined) {

            $.msgBox({
                title: "Subscription Plan",
                content: "Please select plan to subscribe.",
                type: "info",
                buttons: [{ value: "Ok"}],
                success: function (result) {
                },
                afterShow: function () { $('[name=Ok]').focus(); }
            });

        }
        if (selectedPlan == 1) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 1})';
        }
        else if (selectedPlan == 2) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 2})';
        }
        else if (selectedPlan == 3) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 3})';
        }
        else if (selectedPlan == 4) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 4})';
        }
        else if (selectedPlan == 5) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 5})';
        }
        else if (selectedPlan == 6) {
            window.location = '@Url.Action("Subscribe", "SelectSubscription", new {selectedPlan = 6})';
        }

    });

</script>

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/SelectSubscription/Receipt.cshtml
@model PlanguruSubscription.Models.Customer
@{
    ViewData["Title"] = "PlanGuru Subscription - Signup Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header>
    <link rel="stylesheet" href="@Url.Content("~/themes/default/recurly.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />
</header>

<div id="billing-info" class="section">
    <div id="recurly-subscribe">
        <h2 class="heading">
            Signup Confirmation
        </h2>
        <div style="width:90%;margin:0px 40px;">
            <br />
            <p>Thank you for subscribing to PlanGuru. Shortly you will receive 2 emails:</p><br />
           
            <ol>
                <li>A confirmation email from <a href="mailto:orders@planguru.com">orders@planguru.com</a> with your Invoice</li>
                <li>Another email from <a href="mailto:orders@planguru.com">orders@planguru.com</a> with your PlanGuru downloads & licenses</li>
            </ol>
            <br />
            <p>If you don’t see these emails within the next few minutes, please check the spam or junk folders in your inbox. If you still cannot find either email, please contact us at <a href="mailto:support@planguru.com">support@planguru.com</a> </p>
            <br/>
            <br/>
            <br/>
            <br/>
        </div>
    </div>
    <div style="float: left; margin-left: 20px;">
        @if (((string)TempData["Message"] != null))
        {

            <label class="success">
                @TempData["Message"].ToString()
            </label>
        }
        @if (((string)TempData["ErrorMessage"] != null))
        {
            <label class="error">
                @TempData["ErrorMessage"].ToString()
            </label>
        }
    </div>
</div>

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/SelectSubscription/SubscribeOld.cshtml
@model PlanguruSubscription.Models.Customer
@using PlanguruSubscription
@using System.Collections.Generic
@{
    ViewBag.Title = "Subscribe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header>
    <link rel="stylesheet" href="@Url.Content("~/themes/default/recurly.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />
    @*<script src="https://js.recurly.com/v4/recurly.js"></script>*@
    <script type="text/javascript" language=javascript src="@Url.Content("~/Recurly/recurly.js")"></script>
</header>
<script>

    $(document).ready(function () {

        function SubscriptionResponse(response) {

            Recurly.postResult('@Url.Action("Receipt", "SelectSubscription")', response, null);
        }

        Recurly.config({
            subdomain: 'new-horizon-software-technologies-inc',
            currency: 'USD'
        });

        Recurly.buildSubscriptionForm({
            target: '#recurly-subscribe',
            // Signature must be generated server-side with a utility method provided in client libraries.
            signature: '@ViewBag.Signature'.replace(/&amp;/g, '&'),
            successHandler: SubscriptionResponse,
            //successURL: 'confirm.aspx',
            planCode: '@ViewBag.Plan', //'planguru-analytics',
            distinguishContactFromBillingInfo: true,
            collectCompany: true,
            enableCoupons: true,
            enableAddOns: true,
            collectPhone: true,
            termsOfServiceURL: 'http://planguru.com/terms-of-service',
            acceptedCards: ['mastercard',
                    'discover',
                    'american_express',
                    'visa'],
            account: {
                accountCode: '@ViewBag.AccountCode',
                firstName: '',
                lastName: '',
                email: '',
                companyName: ''

            },
            billingInfo: {
                firstName: '',
                lastName: '',
                phone: '',
                address1: '',
                address2: '',
                city: '',
                zip: '',
                state: '',
                country: '',
                cardNumber: '',
                CVV: ''
            }
        });

    });
    $(window).load(function () {
        $("div.add_on.last").hide();
        $("div.cost:nth-child(3)").html("$0.00");

        $(".recurly .add_ons .add_on .quantity.field input[type=text]").on('change keyup', function () {
            if($(".recurly .add_ons .add_on .quantity.field input[type=text]").val() == "" || $(".recurly .add_ons .add_on .quantity.field input[type=text]").val() == "0")
            {
                $("div.cost:nth-child(3)").html("$0.00");
                alert("123");
            }
        })
    });
</script>
<div class="headerTable" style="float:right;">
    <table>
        <tr>
            <td style="border:none !important; text-align:left;">
                Subscribe
            </td>
        </tr>
    </table>
</div>
<form id="Recurly-Subscription" runat="server" style="padding-bottom: 20px;">
    <div id="recurly-subscribe" style="margin: 0 0 50px;">
    </div>
</form>