trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Models/SubscribeForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlanguruSubscription.Models
{
    public class SubscribeForm
    {
        public string Coupen_Code { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Subscriber_Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string RecurlyToken { get; set; }
        public string PreferedLanguage { get; set; }
        //subscribe plan related thing
        public string PlanCode { get; set; }
        public string PlanName { get; set; }
        public string PlanRate { get; set; }
        public string PlanFrequency { get; set; }
        public int PlanTypeId { get; set; }
        //addon related detail
        public string AddOnCode { get; set; }
        public string AddOnName { get; set; }
        public double AddOnUnitAmount { get; set; }
        public int Number_Of_Addon { get; set; }
        //coupon code list
        //public List<Recurly.RecurlyAccountCoupon> CoupenList { get; set; }
        public List<RecurlyNew.Coupon> CoupenList { get; set; }
    }
}

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Controllers/SubscribeController.cs
using PlanguruSubscription.DAL;
using PlanguruSubscription.Models;
using PlanguruSubscription.Modules;
//using Recurly;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecurlyNew;

namespace PlanguruSubscription.Controllers
{
    public class SubscribeController : Controller
    {
        private Utility utility = new Utility();
        private Common common = new Common();
        private ICustomerRepository customerRepository;
        private IUserRepository userRepository;
        private UserRole UserType;
        private User LoginUserInfo;
        private User userInfo;
        private string CustomerId = null;
        private int pageSize;

        public SubscribeController()
        {
            this.userRepository = new UserRepository(new DataAccess());
            this.customerRepository = new CustomerRepository(new DataAccess());
        }

        public SubscribeController(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }
        public SubscribeController(ICustomerRepository customerRepository)
        {
            this.customerRepository = customerRepository;
        }
        //
        // GET: /Subscribe/

        public ActionResult Index()
        {
            return View();
        }



        #region CancelSubscription Part

        [HttpGet()]
        [CustomActionFilter()]
        public bool CancelSubscription(string AccountCode)
        {
            Logger.Log.Info(string.Format("Subscription cancellation started {0}", AccountCode));
            IEnumerable<User> deactivateUsers = null;

            try
            {
                if (((Session["UserType"] != null)) & ((Session["UserInfo"] != null)))
                {
                    UserType = (UserRole)Session["UserType"];
                    LoginUserInfo = (User)Session["UserInfo"];
                    userInfo = utility.UserRepository.GetUsers().Where(u => u.UserId == LoginUserInfo.UserId).SingleOrDefault();
                    AccountCode = UserType.UserRoleId == (int)UserRoles.SAU ? LoginUserInfo.CustomerId.ToString() : AccountCode;
                }

                RecurlyNew.Account acc = RecurlyNew.Accounts.Get(AccountCode);
                var customer = utility.CustomerRepository.GetCustomerById(Convert.ToInt32(AccountCode));
                var plan = utility.SubscriptionPlanRepository.GetSubscriptionPlan(customer.PlanTypeId);
                var RecurlySubscriptionPlan = RecurlyNew.Plans.Get(plan.Plan);

                if ((RecurlyNew.Account.IsExist(AccountCode)))
                {
                    RecurlyNew.Accounts.Close(AccountCode);
                    Logger.Log.Info(string.Format("Account deactivated successfully in PlanGuru of CustomerId- {0}", AccountCode));
                    if ((acc.BillingInfo != null))
                    {
                        var subscription = new RecurlyNew.Subscription(acc, RecurlySubscriptionPlan, "USD");
                        subscription.Terminate(RecurlyNew.Subscription.RefundType.None);
                        Logger.Log.Info(string.Format("Account's subscription cancelled successfully in PlanGuru of CustomerId- {0}", AccountCode));
                        SendEmail(customer, (int)EmailType.SubcriptionCancellation);
                    }
                }

                if ((userInfo.UserRoleId == (int)UserRoles.PGAAdmin | userInfo.UserRoleId == (int)UserRoles.PGASupport))
                {
                    deactivateUsers = from user in utility.UserRepository.GetUsers().Where(x => x.CustomerId == Convert.ToInt32(AccountCode)) select user;
                }
                else
                {
                    deactivateUsers = (from user in utility.UserRepository.GetUsers(Convert.ToInt32(AccountCode), userInfo.UserId) select user).ToList();
                }

                List<int> users = (from du in deactivateUsers select du.UserId).ToList();

                dynamic companyIds = utility.UserCompanyMappingRepository.GetDistinctCompanies(users);

                if ((companyIds != null))
                {
                    foreach (int companyId in companyIds)
                    {
                        utility.CompaniesRepository.DeleteCompany(companyId);
                    }
                    foreach (User User in deactivateUsers)
                    {

                        utility.UserRepository.Delete(User);
                        Logger.Log.Info(string.Format("Account of user:{0} has been deleted, UserId : {1} , UserName : {2} , CustomerId : {3}", User.FirstName, User.UserId, User.UserName, User.CustomerId));
                    }
                }
                utility.UserRepository.Save();

                User subscriberInfo = utility.UserRepository.GetUsers().Where(u => u.CustomerId == Convert.ToInt32(AccountCode) & u.UserRoleId == (int)UserRoles.SAU).FirstOrDefault();

                if ((subscriberInfo != null))
                {
                    utility.UserRepository.Delete(subscriberInfo);
                    utility.UserRepository.Save();
                    Logger.Log.Info(string.Format("Account of user:{0} has been deactivated, UserId : {1} , UserName : {2} , CustomerId : {3}", userInfo.FirstName, userInfo.UserId, userInfo.UserName, userInfo.CustomerId));
                }





                utility.CustomerRepository.Delete(customer);
                utility.CustomerRepository.Save();

                TempData["Message"] = "Subscription cancelled successfully.";
                Logger.Log.Info(string.Format("Subscription deleted successfully in PLANGURU database of ACCOUNT-CODE  {0}", AccountCode));


                if ((userInfo.UserRoleId == (int)UserRoles.SAU | userInfo.UserRoleId == (int)UserRoles.SSU))
                {
                    Response.Cookies["ASP.NET_SessionId"].Value = string.Empty;
                    Response.Cookies["ASP.NET_SessionId"].Expires = DateTime.Now.AddMonths(-20);

                    HttpContext.Session.Clear();
                    HttpContext.Session.Abandon();
                    return true;

                }
                else if ((userInfo.UserRoleId < (int)UserRoles.SAU))
                {
                    return true;
                }

                return true;
            }
            catch (DataException dataEx)
            {
                TempData["ErrorMessage"] = string.Concat("Unable to cancel Subscription - ", dataEx.Message);
                Logger.Log.Error(string.Format("Unable to cancel Subscription, AccountCode- {0} with Message- {1} " + Environment.NewLine + "Stack Trace: {2}", AccountCode, dataEx.Message, dataEx.StackTrace));
                return false;
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = string.Concat("Unable to cancel Subscription-", ex.Message);
                Logger.Log.Error(string.Format("Unable to cancel Subscription, AccountCode- {0} with Message- {1} " + Environment.NewLine + "Stack Trace: {2}", AccountCode, ex.Message, ex.StackTrace));
                return false;
            }
            finally
            {
                Logger.Log.Info(string.Format("Execution Ended"));
            }
        }


        //[CustomActionFilter()]
        //public ActionResult CancelSubscription(string AccountCode)
        //{
        //    Logger.Log.Info(string.Format("Subscription cancellation started {0}", AccountCode));
        //    IEnumerable<User> deactivateUsers = null;

        //    try
        //    {
        //        if (((Session["UserType"] != null)) & ((Session["UserInfo"] != null)))
        //        {
        //            UserType = (UserRole)Session["UserType"];
        //            LoginUserInfo = (User)Session["UserInfo"];
        //            userInfo = utility.UserRepository.GetUsers().Where(u => u.UserId == LoginUserInfo.UserId).SingleOrDefault();
        //            AccountCode = UserType.UserRoleId == (int)UserRoles.SAU ? LoginUserInfo.CustomerId.ToString() : AccountCode;
        //        }


        //        RecurlyAccount acc = RecurlyAccount.Get(AccountCode);
        //        var customer = utility.CustomerRepository.GetCustomerById(Convert.ToInt32(AccountCode));

        //        if ((RecurlyAccount.IsExist(AccountCode)))
        //        {
        //            RecurlyAccount.CloseAccount(AccountCode);
        //            Logger.Log.Info(string.Format("Account deactivated successfully in PlanGuru of CustomerId- {0}", AccountCode));
        //            if ((acc.BillingInfo != null))
        //            {
        //                RecurlySubscription.TerminateSubscription(AccountCode);
        //                Logger.Log.Info(string.Format("Account's subscription cancelled successfully in PlanGuru of CustomerId- {0}", AccountCode));
        //                SendEmail(customer, (int)EmailType.SubcriptionCancellation);
        //            }
        //        }

        //        if ((userInfo.UserRoleId == (int)UserRoles.PGAAdmin | userInfo.UserRoleId == (int)UserRoles.PGASupport))
        //        {
        //            deactivateUsers = from user in utility.UserRepository.GetUsers().Where(x => x.CustomerId == Convert.ToInt32(AccountCode)) select user;
        //        }
        //        else
        //        {
        //            deactivateUsers = (from user in utility.UserRepository.GetUsers(Convert.ToInt32(AccountCode), userInfo.UserId) select user).ToList();
        //        }

        //        List<int> users = (from du in deactivateUsers select du.UserId).ToList();

        //        dynamic companyIds = utility.UserCompanyMappingRepository.GetDistinctCompanies(users);

        //        if ((companyIds != null))
        //        {
        //            foreach (int companyId in companyIds)
        //            {

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/Subscribe/EditSubscription.cshtml
@using PlanguruSubscription.Models
@model PlanguruSubscription.Models.Customer
@using System.Collections.Generic
@{
    ViewData["Title"] = "PlanGuru Analytics | Edit Subscription";
    if ((Session["action"] != null))
    {

        if ((Session["action"] == "SetDefaultAnalysis" | Session["action"] == "GetAnalyses"))
        {
            Layout = null;
            Session.Remove("action");
        }
    }
    else
    {
        Layout = "~/Views/Shared/_AnalyticsMaster.cshtml";
    }

    UserAccess ua = new UserAccess();
    if ((Session["UserAccess"] != null))
    {
        ua = (UserAccess)Session["UserAccess"];
    }

}

<div class="headerTable" style="float: right">
    <table>
        <tr>
            <td align="left" width="70%">
                <div class="breadscrum"><a href='@Url.Action("Index", "User")'>Home</a><span> > </span>Edit Billing Information</div>
            </td>
            @if (ua.ViewSubscription == true)
            {
                <td align="right" width="12%" class="add button_example" href='@Url.Action("Index", "Subscribe")'>
                    <img src='@Url.Content("~/Content/Images/List.png")' class="analysisIcon" style="margin-right:5px;float:left;" />Subscriber List
                </td>
            }
        </tr>
    </table>
</div>
<br /><br />
<header>
    <link rel="stylesheet" href="@Url.Content("~/themes/default/recurly.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />
    <script type="text/javascript" language=javascript src="@Url.Content("~/Recurly/recurly.js")"></script>
</header>
<script type="text/javascript" language="javascript">

    function cancelEvent() {
            var url = '@Url.Action("Index", "User")';
            window.location = url;
    }

    $(document).ready(function () {

        IsSessionAlive();
        function SubscriptionResponse(response) {
            Recurly.postResult('@Url.Action("UpdateSubscription", "Subscribe")', response, null);

        }

        Recurly.config({
            subdomain: 'new-horizon-software-technologies-inc',
            currency: 'USD'
        });

        Recurly.buildBillingInfoUpdateForm({
            target: '#recurly-update-billing-info',
            // Signature must be generated server-side with a utility method provided in client libraries.
            signature: '@ViewBag.Signature'.replace(/&amp;/g, '&'),
            accountCode: '@Model.CustomerId',
            //successURL: 'confirmation.html',
            addressRequirement: 'full',
            successHandler: SubscriptionResponse,
            planCode: 'planguru-analytics',
            distinguishContactFromBillingInfo: true,
            account: {
                firstName: '',
                lastName: '',
                email: '',
                companyName: ''
            },
            acceptedCards: ['mastercard',
                    'discover',
                    'american_express',
                    'visa'],
            billingInfo: {
                firstName: '',
                lastName: '',
                phone: '',
                address1: '',
                address2: '',
                city: '',
                zip: '',
                state: '',
                country: '',
                cardNumber: '',
                CVV: ''
            }
        });
    });
</script>
<form id="Recurly-Subscription" runat="server" style="padding-bottom: 20px;">
    <div id="recurly-update-billing-info" style="margin-bottom:0px;">
    </div>
</form>

trunk/PlanGuru-Internal/PlanguruSubscription/PlanguruSubscription/Views/Subscribe/UpdateSubscription.cshtml
@model PlanguruSubscription.Models.Customer
@{
    ViewData["Title"] = "PlanGuru Analytics | Update Subscription";
    if ((Session["action"] != null))
    {

        if ((Session["action"] == "SetDefaultAnalysis" | Session["action"] == "GetAnalyses"))
        {
            Layout = null;
            Session.Remove("action");
        }
    }
    else
    {
        Layout = "~/Views/Shared/_AnalyticsMaster.cshtml";
    }
    
}
<header>
    <link rel="stylesheet" href="@Url.Content("~/themes/default/recurly.css")" type="text/css" />
    <link rel="stylesheet" href="@Url.Content("~/themes/default/examples.css")" type="text/css" />
</header>
<h2>Subscription updated successfully</h2>

<div id="billing-info" class="section">
    <div id="recurly-subscribe">
        <h2 class="heading">
            Billing Information
        </h2>
        <!-- table: billing info -->
        <table style="width: 100%;">
            <tbody>
                <tr>
                    <td style="text-align:right;width:45%;font-weight:bold;">
                        Subscription Plan:
                    </td>
                    <td style="text-align:left;padding-left:20px;">
                        PlanGuru Analytics
                    </td>
                </tr>
                <tr>
                    <td scope="row" style="text-align:right;width:45%;font-weight:bold;">
                        First Name:
                    </td>
                    <td style="text-align:left;padding-left:20px;">
                        @Model.CustomerFirstName
                    </td>
                </tr>
                <tr>
                    <th scope="row" style="float:right;margin-right:5px;">
                        Last Name:
                    </th>
                    <td style="text-align:left;padding-left:20px;">
                        @Model.CustomerLastName
                    </td>
                </tr>
                <tr>
                    <th scope="row" style="float:right;margin-right:5px;">
                        Email Id:
                    </th>
                    <td style="text-align:left;padding-left:20px;">
                        @Model.CustomerEmail
                    </td>
                </tr>
                <tr>
                    <th scope="row" style="float:right;margin-right:5px;">
                        Credit Card:
                    </th>
                    <td style="text-align:left;padding-left:20px;">
                        XXXX-XXXX-XXXX-@ViewBag.CreditCardLastFourDigit (@ViewBag.CreditCardType)
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="receipt">
        </p>
    </div>
</div>